"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['diegoMOV_player.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'assets/app_icon.icns',
    'plist': {
        'CFBundleName': 'DiegoMOV Player',
        'CFBundleShortVersionString': '1.1',
        'CFBundleVersion': '1.1',
        'CFBundleIdentifier': 'com.yourdomain.diegomovplayer',
        'CFBundleIconFile': 'app_icon.icns',
    },
}


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
