/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117495-ge347b4ff31-20241014"
#endif /* AVUTIL_FFVERSION_H */
